import SessionDomain

typealias FooterActivity = SessionDomain.FooterActivity
typealias ForegroundActivity = SessionDomain.ForegroundActivity
typealias ActivityTracker = SessionDomain.ActivityTracker
typealias StatusEventClock = SessionDomain.StatusEventClock
typealias SessionSemanticsState = SessionDomain.SessionSemanticsState
typealias SessionSemantics = SessionDomain.SessionSemantics
